// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1754);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1593360830);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f5ef8001-88b9-479c-bf72-ea3873af7426}");
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1593360839527");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1593364439527");
user_pref("browser.search.region", "AT");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200403171148");
user_pref("browser.slowStartup.averageTime", 5593);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200403171148");
user_pref("browser.startup.homepage_override.mstone", "68.7.0");
user_pref("browser.startup.lastColdStartupCheck", 1593362905);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.7.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200403171148");
user_pref("extensions.lastAppVersion", "68.7.0");
user_pref("extensions.lastPlatformVersion", "68.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"c33ceca8-5322-45c6-b678-b79937b773af\",\"fxmonitor@mozilla.org\":\"b31f6cf1-2993-4677-ab28-5261ed2118a7\",\"screenshots@mozilla.org\":\"89483db6-e93f-4174-aa7e-e2f1969724c3\",\"webcompat-reporter@mozilla.org\":\"3e298e8f-6184-4886-9156-8420b63bfbbd\",\"webcompat@mozilla.org\":\"677cf729-5107-4f68-9f9d-5867e5e942fe\",\"default-theme@mozilla.org\":\"9f083166-fc8d-4d06-9cac-9f53cf7d335e\",\"google@search.mozilla.org\":\"17c0e2c0-a214-4a41-a668-0bcbf5f020fc\",\"amazondotcom@search.mozilla.org\":\"a1d20c9c-4fdf-4dfd-a00f-f034bffa84d5\",\"bing@search.mozilla.org\":\"437d19d3-3f80-4930-9d27-a42add2c8cc4\",\"ddg@search.mozilla.org\":\"13f07a2b-d5e2-49dc-860a-6a84d535357c\",\"ebay@search.mozilla.org\":\"6ed9f04a-fdff-4920-9a36-e932e2485665\",\"twitter@search.mozilla.org\":\"268c5fe5-6ec7-4e3a-93c2-19d33031f310\",\"wikipedia@search.mozilla.org\":\"67d45238-a274-4871-8958-6bae9d5dd553\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "0aab397b-fd19-4ad3-82b0-3ef64a119e84");
user_pref("security.sandbox.plugin.tempDirSuffix", "73ecce8e-1b08-4beb-9cf6-9dcc116182d1");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1593362902);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200403171148");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
